version: '2'

services:
  neo4j:
    image: neo4j:latest
    volumes:
      - /home/fagh/Stiahnuté/tweets2021.dump:/tmp/dump
      - ./stopwords:/var/lib/neo4j/import/stopwords

    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
#      - NEO4J_dbms_memory_heap_initial__size=4024M
#      - NEO4J_dbms_memory_heap_max__size=4024M
      - NEO4J_dbms_default__database=PDT
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*


